# -*- coding: utf-8 -*-
"""assistant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NM1vGKRN47-jmjhINk10M6MISJBg-sfr
"""

import json
import faiss
import numpy as np
import requests
from sentence_transformers import SentenceTransformer
from typing import List, Dict
from .config import *

class BuildingCodeAssistant:
    def __init__(self):
        self.index = faiss.read_index(INDEX_PATH)
        with open(METADATA_PATH, "r", encoding="utf-8") as f:
            self.metadata = json.load(f)
        self.model = SentenceTransformer(EMBEDDING_MODEL)

    def search(self, query: str, top_k: int = 3) -> List[Dict]:
        """Семантический поиск по индексу"""
        query_embed = self.model.encode([query])
        distances, indices = self.index.search(np.array(query_embed), top_k)
        return [self.metadata[i] for i in indices[0] if i < len(self.metadata)]

    def generate_answer(self, query: str) -> str:
        """Генерация ответа через YandexGPT"""
        context_docs = self.search(query)
        context = "\n".join(f"{doc['source']}, п.{doc.get('clause', '?')}:\n{doc['text']}" 
                          for doc in context_docs)

        prompt = f"""
        Ты — эксперт по строительным нормам РФ c 20 летним стажем. Отвечай строго на основе предоставленного контекста.
        Если информации нет — ответь "Требование не регламентировано в предоставленных документах.

        Контекст:
        {context}
        Вопрос: {query}
        Требуемый формат:
          1. Прямой ответ на вопрос
          2. Номер пункта СП (если указан)
          3. Название документа
          4. Точная цитата из норматива

        Если необходимо вывести таблицу с данными, то ты должен ее сгенерировать.
        """

        response = requests.post(
            "https://llm.api.cloud.yandex.net/foundationModels/v1/completion",
            headers={"Authorization": f"Api-Key {YC_API_KEY}"},
            json={
                "modelUri": YC_MODEL_URI,
                "messages": [{"role": "user", "text": prompt}],
                "completionOptions": {"temperature": 0.1}
            },
            timeout=10
        )
        return response.json()['result']['alternatives'][0]['message']['text']

